# **NUMPY ARITHMETIC OPERATIONS**

Copying and Viewing

Copying and Viewing


*  Copying : a new file will be created(copied)
*   Viewing : simply a shallow copy (viewing copy), the changes in the original file will be visible in the view file



In [ ]:
import numpy as np

# creating the array
arr = np.array([1,2,3])
print("Array =",arr)

# copy of the array
acopy = arr.copy()
print("Copy =",acopy)

# view of the array
aview = arr.view()
print("View =",aview)

# changing the array 
arr[0] = 69
print("Changed array =",arr)

# checking the changes
print("copy again =",acopy)
print("view again =",aview)


Array = [1 2 3]
Copy = [1 2 3]
View = [1 2 3]
Changed array = [69  2  3]
copy again = [1 2 3]
view again = [69  2  3]


Stacking 1D arrays


*   vstack: stacks arrays in sequence vertically (row wise)
*   hstack: 
*   column_stack
*   row_stack





In [ ]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr_vstack = np.vstack((arr1,arr2))
print("vstacked array =\n",arr_vstack)

arr_hstack = np.hstack((arr1,arr2))
print("hstacked array =\n",arr_hstack)

arr_rowstack = np.row_stack((arr1,arr2))
print("rowstacked array =\n",arr_rowstack)

arr_columnstack = np.column_stack((arr1,arr2))
print("columnstacked array =\n",arr_columnstack)

vstacked array =
 [[1 2 3]
 [4 5 6]]
hstacked array =
 [1 2 3 4 5 6]
rowstacked array =
 [[1 2 3]
 [4 5 6]]
columnstacked array =
 [[1 4]
 [2 5]
 [3 6]]


Stacking 2D & 3D arrays

In [ ]:
# https://www.geeksforgeeks.org/numpy-stack-in-python/

Data Sorting

In [ ]:
import numpy as np

arr1 = np.array([56,21,5,22])
arr2 = np.array([[2,3,1],[21,14,5]])
# sorted 1D array
print("sorted array =",np.sort(arr1))
# sorted 2D array
print("sorted array =\n",np.sort(arr2))

# reverse sorted 1Darray
print("sorted array in descending order =", np.sort(arr1)[::-1])
# reverse sorted 2D array
print("sorted array in descending order =\n", np.sort(arr2, axis=None, kind='quicksort')[::-1])


sorted array = [ 5 21 22 56]
sorted array =
 [[ 1  2  3]
 [ 5 14 21]]
sorted array in descending order = [56 22 21  5]
sorted array in descending order =
 [21 14  5  3  2  1]


Filtering

In [ ]:
import numpy as np
arr = np.array([41,42,43,44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


SEQUENCE GENERATION

1.  METHOD_1: list to array conversion
2.  METHOD_2: **np.arange()** function




In [ ]:
import numpy as np

# converting list to array

# this is a list of even numbers from 0 to 100
list1 = [x for x in range(0,101,2)]

# conversion
a = np.array(list1)
print(type(a))              # ndarray means: n-dimensional array

# printing the list as array
print("array =",a)

In [ ]:
b = np.arange(0,101,2)
print(b)

**reshape()** : used to reshape the array

In [ ]:
c = np.arange(9,0,-1).reshape(3,3)     #rows=3 and columns=3
print(c)

**empty()**: used to return a new array of give shape and type. Has random values and uninitialised entries

In [ ]:
# creates an array of 3 rows, 3 columns with random integer values
some_array = np.empty((3,3),int)
print(some_array)

getting the postitions (indexes) where elements of 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match

*   **where()** function : gives the indees of the elements according to the conditions



In [ ]:
# find the indexes where elements are common
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])
print(np.where(a==b))


# finding the indexes of the even elements
arr = np.array([10,20,33,45,58,68,74,89])
x = np.where(arr%2 == 0)
print(x)

**searchsorted()** function : performs a binary search, and return the index of the given value from the given array


*   **values should be sorted first to get a correct output**



In [ ]:
import numpy as np

# searches for 7 in the sorted array
arr = np.array([6,7,8,9])
x = np.searchsorted(arr,7)
print(x)

# shows wrong inpute when values are not sorted
arr2 = np.array([34,89,12,9])
x = np.searchsorted(arr2,12)
print(x)

1
0


we can use the **side** parameter of **searchsorted()** function to specify the side from which we want the index

In [ ]:
import numpy as np

arr = np.array([6,7,8,9])
x = np.searchsorted(arr,7,side='right')
print(x)

2


searching for multiple values

In [ ]:
import numpy as np

arr = np.array([6,7,8,9])
x = np.searchsorted(arr,[7,8])
print(x)

**Broadcasting**: describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.
*   https://numpy.org/doc/1.20/user/theory.broadcasting.html
*   https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm


In [ ]:
import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print("First array\n",a,"\n")
print("Second array\n",b,"\n")
print('First Array + Second Array\n',a+b,)

In [ ]:
from numpy import array
a = array([1.0,2.0,3.0])
b = 2.0
print(a * b)

[2. 4. 6.]


# **NUMPY STATISTICAL OPERATIONS**

Common Statistical Operations

In [ ]:
arr = np.array([1,2,3,4,5,9,6,7,8,9,9])

# standard deviation
print(np.std(arr))

# minimum
print(np.min(arr))

# summation
print(np.sum(arr))

# mean
print(np.mean(arr))

# variance
print(np.var(arr))

# mode (required scipy module)
import scipy
from scipy import stats
print("Most frequent element = ",stats.mode(arr)[0],"occurring",stats.mode(arr)[1],"times")


2.7990553306073913
1
63
5.7272727272727275
7.834710743801653
Most frequent element =  [9] occurring [3] times


<ipython-input-15-2aaa7928208e>:21: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print("Most frequent element = ",stats.mode(arr)[0],"occurring",stats.mode(arr)[1],"times")


Here, in the above example, the order of 1st array is 4x3 and order of 2nd is 1x3. So the program broadcasts the 2nd array to become 4x3 by repeating the elements, and then the operation is done

Here, in the above example,  the orders of the arrays are different. Hence, the smaller array is broadcasted to be multiplied with the 1st array

# **PRACTICAL 3**

*   using **loadtxt()**: 
https://numpy.org/doc/stable/reference/generated/numpy.
loadtxt.html

https://www.w3resource.com/numpy/array-creation/loadtxt.php



*   Important Parameters: 
> 1.   fname: name of the file
2.   dtype(optional): data type
3.   delimite(optional): separating character (comma for csv)
4.  skiprows(optional): skips the first n rows, including comments









**PRACTICAL3 **
1.   get a dataset (csv)
2.   get it into a list
3.   put that into an array
4.   and then perform the 5 numpy operations


In [ ]:
import numpy as np

# loading the csv file into an array using np.loadtext
arr = np.loadtxt("emp.csv",delimiter=',',dtype=str,skiprows=1)  
# skiprows parameter will skip the 1st row (header row)
print(arr,"\n")

#extracting data into lists
sal = []
exp = []
for i in arr:
    sal.append(int(i[2]))
    exp.append(int(i[3]))
print("Sal list:",sal)
print("Experience list:",exp)
print()

# converting lists to arrays
arr_sal = np.array(sal)
arr_exp = np.array(exp)
print("Sal Array: ",arr_sal)
print("Experience Array:",arr_exp)
print()


# NUMPY OPERATIONS
# 1) element-wise addition
print("1)Added array = ",arr_sal + arr_exp)

# 2) element-wise multiplications
print("2)Multiplied array =",arr_sal * arr_exp)

# 3) concatenation
combo = np.concatenate((arr_sal,arr_exp))
print("3)Combined array: ",combo)

# 4) reshaping
reshaped = np.reshape(combo,(4,4))
print("4)Reshaped array: ",reshaped)

# 5) mean
print("5)Mean Salary:",np.mean(arr_sal))

# 6) minimum experience
print("6)Min Exp:",np.min(arr_exp))


[['E001' 'Shawn' '1000' '2' 'sales']
 ['E002' 'Donald' '1500' '3' 'quality ']
 ['E003' 'Hannah' '3000' '5' 'marketing']
 ['E004' 'Roger' '2500' '1' 'finances']
 ['E005' 'Katherine' '2200' '6' 'hr']
 ['E006' 'Jack' '2500' '4' 'sales']
 ['E007' 'John' '5000' '7' 'management']
 ['E008' 'Shannon' '1600' '1' 'sales']] 

Sal list: [1000, 1500, 3000, 2500, 2200, 2500, 5000, 1600]
Experience list: [2, 3, 5, 1, 6, 4, 7, 1]

Sal Array:  [1000 1500 3000 2500 2200 2500 5000 1600]
Experience Array: [2 3 5 1 6 4 7 1]

1)Added array =  [1002 1503 3005 2501 2206 2504 5007 1601]
2)Multiplied array = [ 2000  4500 15000  2500 13200 10000 35000  1600]
3)Combined array:  [1000 1500 3000 2500 2200 2500 5000 1600    2    3    5    1    6    4
    7    1]
4)Reshaped array:  [[1000 1500 3000 2500]
 [2200 2500 5000 1600]
 [   2    3    5    1]
 [   6    4    7    1]]
5)Mean Salary: 2412.5
6)Min Exp: 1
