In [2]:
import numpy as np

arr1=np.array([1,2,3])
arr2=arr1.copy()

arr2[0]=4

print(arr1)
print(arr2)

[1 2 3]
[4 2 3]


In [3]:
import numpy as np

arr1=np.array([1,2,3])
arr2=arr1.view()

arr2[0]=4

print(arr1)
print(arr2)

[4 2 3]
[4 2 3]


In [4]:
import numpy as np

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

arr3=np.vstack((arr1,arr2))

print(arr3)

[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np

arr=np.array([3,4,2,1,9])
print(np.sort(arr))

[1 2 3 4 9]


In [11]:
import numpy as np

arr = np.array([3, 4, 2, 1, 9])
sorted_arr = np.sort(arr)[::-1]
print(sorted_arr)


[9 4 3 2 1]


In [8]:
import numpy as np

arr=np.array([[3,4,2],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [10]:
import numpy as np

arr = np.array([[3, 4, 2], [5, 0, 1]])

sorted_arr = np.sort(arr)[::-1]
print(sorted_arr)


[[0 1 5]
 [2 3 4]]


In [15]:
import numpy as np
list1= [x for x in range(0,101,2)]
a=np.array(list1)
print(a)
print(type(list1))
print(type(a))

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
<class 'list'>
<class 'numpy.ndarray'>


In [20]:
import numpy as np
b = np.arange(50,0,-1).reshape(5,10)
print(b)

[[50 49 48 47 46 45 44 43 42 41]
 [40 39 38 37 36 35 34 33 32 31]
 [30 29 28 27 26 25 24 23 22 21]
 [20 19 18 17 16 15 14 13 12 11]
 [10  9  8  7  6  5  4  3  2  1]]


In [21]:
b = np.arange(9,0,-1).reshape(3,3)
print(b)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [22]:
nparray=np.empty((3,3),int)
nparray

array([[           66100960,                   0, 8367800571912007268],
       [7598822093868984680, 7595074976640691823, 7307218076941837686],
       [7598258805938200686, 6485194958716236910,                 160]])

In [23]:
import numpy as np
arr=np.array([10,20,30,40,50,40,64])
x=np.where(arr==40)
print(x)

(array([3, 5]),)


In [24]:
import numpy as np
arr=np.array([10,20,30,40,50,40,64])
x=np.where(arr%2==0)
print(x)

(array([0, 1, 2, 3, 4, 5, 6]),)


In [27]:
import numpy as np
arr=np.array([10,20,5,7,6,8,7,75,54.7])
x=np.searchsorted(arr,7)
print(x)

5


In [29]:
import numpy as np
arr=np.array([10,20,5,7,6,8,75,54.7])
x=np.searchsorted(arr,7,side='right')
print(x)


5


In [36]:
import numpy as np
arr = np.array([10,30,50,70])
x=np.searchsorted(arr,[10,70])
print(arr)
print(x)

[10 30 50 70]
[0 3]


In [42]:
array1=np.array([1,2,3,4,5,9,6,7,8,9,9])
#standard deviation
print(np.std(array1))
#minimum
print(np.min(array1))
#summation
print(np.sum(array1))
#median
print(np.median(array1))
#mean
print(np.mean(array1))
#mode
from scipy import stats
print("Most frequent element=",stats.mode(array1)[0])
print("Number of occurrences =",stats.mode(array1)[1])
#variance
print(np.var(array1))

2.7990553306073913
1
63
6.0
5.7272727272727275
Most frequent element= [9]
Number of occurrences = [3]
7.834710743801653


<ipython-input-42-fa4271cfcf80>:14: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print("Most frequent element=",stats.mode(array1)[0])
<ipython-input-42-fa4271cfcf80>:15: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print("Number of occurrences =",stats.mode(arr